---
- name: Gathering information about the load balancer
  hosts: lb
  connection: local

  tasks:
     - name: Gather information
       f5networks.f5_modules.bigip_device_info:
         gather_subset: 
            - ltm-pools
            - nodes
            - self-ips
            - virtual-servers
         provider:
           server: "172.29.224.100"
           user: "{{ ansible_user }}"
           password: "{{ ansible_ssh_pass }}"
           validate_certs: no
       register: configuration

     - name: Save facts to file 
       copy: 
         content: "{{ configuration | to_nice_json }}"
         dest: /mnt/c/Users/JoshC/Desktop/SDN/F5LoadBalancing-with-Ansible/F5facts
         