---
- name: Creating and adding nodes to pool
  hosts: lb
  connection: local

  tasks:
     - name: Create and add nodes
       f5networks.f5_modules.bigip_pool_member:
         pool: "webservers"
         host: "{{ item.host }}"
         name: "{{ item.name }}"
         port: 80
         provider:
           server: "172.29.224.100"
           user: "{{ ansible_user }}"
           password: "{{ ansible_ssh_pass }}"
           validate_certs: no
       loop:
         - { name: 'webserver1', host: 192.168.122.240 }
         - { name: 'webserver2', host: 192.168.122.243 }