---
- name: Changing hostname of the device
  hosts: lb
  connection: local

  tasks:
     - name: Changing hostname
       f5networks.f5_modules.bigip_hostname:
         hostname: jaeouks.f5bigip.localdomain
         provider:
           server: "172.29.224.100"
           user: "{{ ansible_user }}"
           password: "{{ ansible_ssh_pass }}"
           validate_certs: no
         