---
- name: Changing admin password
  hosts: lb
  connection: local

  tasks:
     - name: Changing password
       f5networks.f5_modules.bigip_user:
         username_credential: admin
         password_credential: myf5password
         provider:
           server: "172.29.224.100"
           user: "{{ ansible_user }}"
           password: "{{ ansible_ssh_pass }}"
           validate_certs: no
         