---
- name: Creating a virtual server with a pool
  hosts: lb
  connection: local

  tasks:
     - name: Adding virtual server
       f5networks.f5_modules.bigip_virtual_server:
         name: "my-virtual-server"
         destination: "10.88.111.250"
         port: 80
         pool: "webservers"
         snat: "Automap"
         provider:
           server: "172.29.224.100"
           user: "{{ ansible_user }}"
           password: "{{ ansible_ssh_pass }}"
           validate_certs: no
         